apiVersion: v1
kind: Service
metadata:
  name: nexent-config
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5010
      targetPort: 5010
      name: http
  selector:
    app: nexent-config
