apiVersion: v1
kind: Secret
metadata:
  name: nexent-secrets
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook-weight": "-3"
type: Opaque
data:
  ELASTIC_PASSWORD: {{ .Values.secrets.elasticPassword | b64enc | quote }}
  {{- if .Values.secrets.elasticsearchApiKey }}
  ELASTICSEARCH_API_KEY: {{ .Values.secrets.elasticsearchApiKey | b64enc | quote }}
  {{- end }}

  NEXENT_POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}

  MINIO_ROOT_USER: {{ .Values.secrets.minio.rootUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.rootPassword | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minio.accessKey | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minio.secretKey | b64enc | quote }}

  SSH_USERNAME: {{ .Values.secrets.ssh.username | default "nexent" | b64enc | quote }}
  SSH_PASSWORD: {{ .Values.secrets.ssh.password | default "nexent@2025" | b64enc | quote }}

  {{- if eq .Values.global.deploymentVersion "full" }}
  {{- if .Values.secrets.supabase.jwtSecret }}
  JWT_SECRET: {{ .Values.secrets.supabase.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.supabase.secretKeyBase }}
  SECRET_KEY_BASE: {{ .Values.secrets.supabase.secretKeyBase | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.supabase.vaultEncKey }}
  VAULT_ENC_KEY: {{ .Values.secrets.supabase.vaultEncKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.supabase.anonKey }}
  SUPABASE_KEY: {{ .Values.secrets.supabase.anonKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.supabase.serviceRoleKey }}
  SERVICE_ROLE_KEY: {{ .Values.secrets.supabase.serviceRoleKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.supabase.postgresPassword }}
  SUPABASE_POSTGRES_PASSWORD: {{ .Values.secrets.supabase.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.supabase.gotrueDbUrl }}
  GOTRUE_DB_DATABASE_URL: {{ .Values.secrets.supabase.gotrueDbUrl | b64enc | quote }}
  {{- end }}
  {{- end }}
