apiVersion: v2
name: nexent-config
description: Nexent Config Service - Management service for configuration
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - nexent
  - config
  - management
maintainers:
  - name: Nexent Team
dependencies:
  - name: nexent-common
    version: 0.1.0
    repository: "file://../nexent-common"
