apiVersion: v2
name: nexent-redis
description: Nexent Redis - In-memory data store
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - nexent
  - redis
  - cache
maintainers:
  - name: Nexent Team
dependencies:
  - name: nexent-common
    version: 0.1.0
    repository: "file://../nexent-common"
