replicaCount: 1

image:
  repository: redis
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m

storage:
  size: 5Gi

persistence:
  mode: local
  storageClassName: nexent-local
  accessModes:
    - ReadWriteMany
  localPath: "/var/lib/nexent-data/nexent-redis"
  existingClaim: ""
