"""Day-one capability profile catalog for ModelCapacityResolver.

Source of truth: W1 ADR at
`doc/working/context-management-workstreams/W1_ADR_Capability_Catalog_Storage_and_Fingerprint.md`.

This module owns the approved catalog data. The SDK resolver
(`sdk/nexent/core/models/capacity_resolver.py`) takes the catalog as a parameter;
it does not import this module directly. Backend services read CATALOG here and
pass it through to the resolver.

Changes to entries: bump the per-entry `capability_profile_version` integer
suffix AND `CATALOG_REVISION` in one PR. Numerical values must be re-verified
against provider documentation at PR merge time.
"""
from __future__ import annotations

import logging
from typing import Dict

from nexent.core.models.capacity_resolver import CapabilityProfile, ProfileKey

logger = logging.getLogger(__name__)


CATALOG_REVISION = "2026-06-27.1"


CATALOG: Dict[ProfileKey, CapabilityProfile] = {
    ("openai", "gpt-4o"): CapabilityProfile(
        provider="openai",
        model_name="gpt-4o",
        capability_profile_version="openai/gpt-4o@1",
        window_shape="combined",
        context_window_tokens=128_000,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="o200k_base",
    ),
    ("openai", "gpt-4.1"): CapabilityProfile(
        provider="openai",
        model_name="gpt-4.1",
        capability_profile_version="openai/gpt-4.1@1",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=32_768,
        default_output_reserve_tokens=8_192,
        tokenizer_family="o200k_base",
    ),
    ("dashscope", "qwen-plus"): CapabilityProfile(
        provider="dashscope",
        model_name="qwen-plus",
        capability_profile_version="dashscope/qwen-plus@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("dashscope", "qwen-turbo"): CapabilityProfile(
        provider="dashscope",
        model_name="qwen-turbo",
        capability_profile_version="dashscope/qwen-turbo@1",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    # Sources cross-checked 2026-06-23:
    # https://help.aliyun.com/zh/model-studio/models (Bailian model catalog)
    # https://llm-stats.com/models/qwen3.7-max (1.0M input, 65.5K output)
    ("dashscope", "qwen3.7-max"): CapabilityProfile(
        provider="dashscope",
        model_name="qwen3.7-max",
        capability_profile_version="dashscope/qwen3.7-max@1",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=65_536,
        default_output_reserve_tokens=8_192,
        tokenizer_family="qwen",
    ),
    ("dashscope", "glm-5.1"): CapabilityProfile(
        provider="dashscope",
        model_name="glm-5.1",
        capability_profile_version="dashscope/glm-5.1@1",
        window_shape="combined",
        context_window_tokens=200_000,
        max_output_tokens=131_072,
        default_output_reserve_tokens=8_192,
        tokenizer_family="chatglm",
    ),
    ("silicon", "Qwen/Qwen3.6-27B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.6-27B",
        capability_profile_version="silicon/qwen3.6-27b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=65_536,
        default_output_reserve_tokens=8_192,
        tokenizer_family="qwen",
    ),
    ("silicon", "Pro/moonshotai/Kimi-K2.6"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/moonshotai/Kimi-K2.6",
        capability_profile_version="silicon/kimi-k2.6@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=131_072,
        default_output_reserve_tokens=8_192,
        tokenizer_family="moonshot",
    ),
    # DeepSeek official platform. Verified 2026-06-23 against
    # https://api-docs.deepseek.com/zh-cn/quick_start/pricing
    # (context 1M, max output 384K for both v4 models). Re-verify at PR
    # merge time per the file header rule.
    #
    # `deepseek-chat` and `deepseek-reasoner` will be deprecated at
    # 2026-07-24 23:59 (Beijing). Per DeepSeek docs they alias to
    # `deepseek-v4-flash` non-thinking and thinking modes respectively,
    # so their capacity profile mirrors `deepseek-v4-flash`. Remove these
    # two entries after the deprecation date.
    ("deepseek", "deepseek-chat"): CapabilityProfile(
        provider="deepseek",
        model_name="deepseek-chat",
        capability_profile_version="deepseek/deepseek-chat@2",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=384_000,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("deepseek", "deepseek-reasoner"): CapabilityProfile(
        provider="deepseek",
        model_name="deepseek-reasoner",
        capability_profile_version="deepseek/deepseek-reasoner@2",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=384_000,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("deepseek", "deepseek-v4-flash"): CapabilityProfile(
        provider="deepseek",
        model_name="deepseek-v4-flash",
        capability_profile_version="deepseek/deepseek-v4-flash@1",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=384_000,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("deepseek", "deepseek-v4-pro"): CapabilityProfile(
        provider="deepseek",
        model_name="deepseek-v4-pro",
        capability_profile_version="deepseek/deepseek-v4-pro@1",
        window_shape="combined",
        context_window_tokens=1_000_000,
        max_output_tokens=384_000,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    # SiliconFlow hosted models. Capacity specs sourced from SiliconFlow pricing
    # page (siliconflow.com/pricing), official model documentation on HuggingFace
    # and GitHub, and provider API docs. Re-verify at PR merge time.
    #
    # DeepSeek models hosted on SiliconFlow. deepseek-ai/ prefixed names are
    # the standard tier; Pro/ prefixed names are the premium tier with the
    # same model weights but higher throughput. Specs from DeepSeek API docs
    # (api-docs.deepseek.com) and SiliconFlow pricing.
    # Catalog key uses "silicon" (hosting provider / DB model_factory), not "deepseek" (model vendor).
    ("silicon", "deepseek-ai/DeepSeek-V4-Pro"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-V4-Pro",
        capability_profile_version="silicon/deepseek-v4-pro-sf@1",
        window_shape="combined",
        context_window_tokens=1_048_576,
        max_output_tokens=384_000,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("silicon", "deepseek-ai/DeepSeek-V4-Flash"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-V4-Flash",
        capability_profile_version="silicon/deepseek-v4-flash-sf@1",
        window_shape="combined",
        context_window_tokens=1_048_576,
        max_output_tokens=384_000,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("silicon", "deepseek-ai/DeepSeek-V3.2"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-V3.2",
        capability_profile_version="silicon/deepseek-v3.2@1",
        window_shape="combined",
        context_window_tokens=164_000,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    ("silicon", "deepseek-ai/DeepSeek-V3.1-Terminus"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-V3.1-Terminus",
        capability_profile_version="silicon/deepseek-v3.1-terminus@1",
        window_shape="combined",
        context_window_tokens=164_000,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    ("silicon", "deepseek-ai/DeepSeek-R1"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-R1",
        capability_profile_version="silicon/deepseek-r1@1",
        window_shape="combined",
        context_window_tokens=163_840,
        max_output_tokens=16_384,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("silicon", "deepseek-ai/DeepSeek-V3"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-V3",
        capability_profile_version="silicon/deepseek-v3@1",
        window_shape="combined",
        context_window_tokens=164_000,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    ("silicon", "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"): CapabilityProfile(
        provider="silicon",
        model_name="deepseek-ai/DeepSeek-R1-0528-Qwen3-8B",
        capability_profile_version="silicon/deepseek-r1-0528-qwen3-8b@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    ("silicon", "Pro/deepseek-ai/DeepSeek-V3.2"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/deepseek-ai/DeepSeek-V3.2",
        capability_profile_version="silicon/deepseek-v3.2-pro@1",
        window_shape="combined",
        context_window_tokens=164_000,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    ("silicon", "Pro/deepseek-ai/DeepSeek-V3.1-Terminus"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/deepseek-ai/DeepSeek-V3.1-Terminus",
        capability_profile_version="silicon/deepseek-v3.1-terminus-pro@1",
        window_shape="combined",
        context_window_tokens=164_000,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    ("silicon", "Pro/deepseek-ai/DeepSeek-R1"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/deepseek-ai/DeepSeek-R1",
        capability_profile_version="silicon/deepseek-r1-pro@1",
        window_shape="combined",
        context_window_tokens=163_840,
        max_output_tokens=16_384,
        default_output_reserve_tokens=8_192,
        tokenizer_family="deepseek",
    ),
    ("silicon", "Pro/deepseek-ai/DeepSeek-V3"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/deepseek-ai/DeepSeek-V3",
        capability_profile_version="silicon/deepseek-v3-pro@1",
        window_shape="combined",
        context_window_tokens=164_000,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="deepseek",
    ),
    # Qwen family on SiliconFlow
    ("silicon", "Qwen/Qwen3.6-35B-A3B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.6-35B-A3B",
        capability_profile_version="silicon/qwen3.6-35b-a3b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3.5-397B-A17B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.5-397B-A17B",
        capability_profile_version="silicon/qwen3.5-397b-a17b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3.5-122B-A10B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.5-122B-A10B",
        capability_profile_version="silicon/qwen3.5-122b-a10b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3.5-35B-A3B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.5-35B-A3B",
        capability_profile_version="silicon/qwen3.5-35b-a3b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3.5-27B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.5-27B",
        capability_profile_version="silicon/qwen3.5-27b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3.5-9B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.5-9B",
        capability_profile_version="silicon/qwen3.5-9b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3.5-4B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3.5-4B",
        capability_profile_version="silicon/qwen3.5-4b@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-VL-32B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-VL-32B-Instruct",
        capability_profile_version="silicon/qwen3-vl-32b-instruct@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-VL-32B-Thinking"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-VL-32B-Thinking",
        capability_profile_version="silicon/qwen3-vl-32b-thinking@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=32_768,
        default_output_reserve_tokens=8_192,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-VL-8B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-VL-8B-Instruct",
        capability_profile_version="silicon/qwen3-vl-8b-instruct@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-VL-8B-Thinking"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-VL-8B-Thinking",
        capability_profile_version="silicon/qwen3-vl-8b-thinking@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=32_768,
        default_output_reserve_tokens=8_192,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-VL-30B-A3B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-VL-30B-A3B-Instruct",
        capability_profile_version="silicon/qwen3-vl-30b-a3b-instruct@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-VL-30B-A3B-Thinking"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-VL-30B-A3B-Thinking",
        capability_profile_version="silicon/qwen3-vl-30b-a3b-thinking@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=32_768,
        default_output_reserve_tokens=8_192,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-Omni-30B-A3B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-Omni-30B-A3B-Instruct",
        capability_profile_version="silicon/qwen3-omni-30b-a3b-instruct@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-Omni-30B-A3B-Thinking"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-Omni-30B-A3B-Thinking",
        capability_profile_version="silicon/qwen3-omni-30b-a3b-thinking@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-Omni-30B-A3B-Captioner"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-Omni-30B-A3B-Captioner",
        capability_profile_version="silicon/qwen3-omni-30b-a3b-captioner@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-Coder-30B-A3B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-Coder-30B-A3B-Instruct",
        capability_profile_version="silicon/qwen3-coder-30b-a3b-instruct@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=65_536,
        default_output_reserve_tokens=8_192,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-30B-A3B-Instruct-2507"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-30B-A3B-Instruct-2507",
        capability_profile_version="silicon/qwen3-30b-a3b-instruct-2507@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-32B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-32B",
        capability_profile_version="silicon/qwen3-32b@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-14B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-14B",
        capability_profile_version="silicon/qwen3-14b@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen3-8B"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen3-8B",
        capability_profile_version="silicon/qwen3-8b@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen2.5-72B-Instruct-128K"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen2.5-72B-Instruct-128K",
        capability_profile_version="silicon/qwen2.5-72b-instruct-128k@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen2.5-72B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen2.5-72B-Instruct",
        capability_profile_version="silicon/qwen2.5-72b-instruct@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen2.5-32B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen2.5-32B-Instruct",
        capability_profile_version="silicon/qwen2.5-32b-instruct@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen2.5-14B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen2.5-14B-Instruct",
        capability_profile_version="silicon/qwen2.5-14b-instruct@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "Qwen/Qwen2.5-7B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="Qwen/Qwen2.5-7B-Instruct",
        capability_profile_version="silicon/qwen2.5-7b-instruct@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    # GLM/Zhipu family on SiliconFlow
    ("silicon", "THUDM/GLM-4-32B-0414"): CapabilityProfile(
        provider="silicon",
        model_name="THUDM/GLM-4-32B-0414",
        capability_profile_version="silicon/glm-4-32b-0414@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="chatglm",
    ),
    ("silicon", "THUDM/GLM-Z1-9B-0414"): CapabilityProfile(
        provider="silicon",
        model_name="THUDM/GLM-Z1-9B-0414",
        capability_profile_version="silicon/glm-z1-9b-0414@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="chatglm",
    ),
    ("silicon", "THUDM/GLM-4-9B-0414"): CapabilityProfile(
        provider="silicon",
        model_name="THUDM/GLM-4-9B-0414",
        capability_profile_version="silicon/glm-4-9b-0414@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="chatglm",
    ),
    ("silicon", "zai-org/GLM-5.2"): CapabilityProfile(
        provider="silicon",
        model_name="zai-org/GLM-5.2",
        capability_profile_version="silicon/glm-5.2@1",
        window_shape="combined",
        context_window_tokens=1_048_576,
        max_output_tokens=131_072,
        default_output_reserve_tokens=8_192,
        tokenizer_family="chatglm",
    ),
    ("silicon", "zai-org/GLM-4.5V"): CapabilityProfile(
        provider="silicon",
        model_name="zai-org/GLM-4.5V",
        capability_profile_version="silicon/glm-4.5v@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="chatglm",
    ),
    ("silicon", "zai-org/GLM-4.5-Air"): CapabilityProfile(
        provider="silicon",
        model_name="zai-org/GLM-4.5-Air",
        capability_profile_version="silicon/glm-4.5-air@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="chatglm",
    ),
    ("silicon", "Pro/zai-org/GLM-5.1"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/zai-org/GLM-5.1",
        capability_profile_version="silicon/glm-5.1-pro@1",
        window_shape="combined",
        context_window_tokens=202_752,
        max_output_tokens=131_072,
        default_output_reserve_tokens=8_192,
        tokenizer_family="chatglm",
    ),
    # Other models on SiliconFlow
    ("silicon", "ByteDance-Seed/Seed-OSS-36B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="ByteDance-Seed/Seed-OSS-36B-Instruct",
        capability_profile_version="silicon/seed-oss-36b-instruct@1",
        window_shape="combined",
        context_window_tokens=524_288,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="seed",
    ),
    ("silicon", "inclusionAI/Ling-flash-2.0"): CapabilityProfile(
        provider="silicon",
        model_name="inclusionAI/Ling-flash-2.0",
        capability_profile_version="silicon/ling-flash-2.0@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="ling",
    ),
    ("silicon", "inclusionAI/Ling-mini-2.0"): CapabilityProfile(
        provider="silicon",
        model_name="inclusionAI/Ling-mini-2.0",
        capability_profile_version="silicon/ling-mini-2.0@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="ling",
    ),
    ("silicon", "MiniMaxAI/MiniMax-M2.5"): CapabilityProfile(
        provider="silicon",
        model_name="MiniMaxAI/MiniMax-M2.5",
        capability_profile_version="silicon/minimax-m2.5@1",
        window_shape="combined",
        context_window_tokens=204_800,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="minimax",
    ),
    ("silicon", "Pro/MiniMaxAI/MiniMax-M2.5"): CapabilityProfile(
        provider="silicon",
        model_name="Pro/MiniMaxAI/MiniMax-M2.5",
        capability_profile_version="silicon/minimax-m2.5-pro@1",
        window_shape="combined",
        context_window_tokens=204_800,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="minimax",
    ),
    ("silicon", "moonshotai/Kimi-K2.7-Code"): CapabilityProfile(
        provider="silicon",
        model_name="moonshotai/Kimi-K2.7-Code",
        capability_profile_version="silicon/kimi-k2.7-code@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=32_768,
        default_output_reserve_tokens=8_192,
        tokenizer_family="moonshot",
    ),
    ("silicon", "nex-agi/Nex-N2-Pro"): CapabilityProfile(
        provider="silicon",
        model_name="nex-agi/Nex-N2-Pro",
        capability_profile_version="silicon/nex-n2-pro@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="qwen",
    ),
    ("silicon", "stepfun-ai/Step-3.5-Flash"): CapabilityProfile(
        provider="silicon",
        model_name="stepfun-ai/Step-3.5-Flash",
        capability_profile_version="silicon/step-3.5-flash@1",
        window_shape="combined",
        context_window_tokens=262_144,
        max_output_tokens=16_384,
        default_output_reserve_tokens=4_096,
        tokenizer_family="step",
    ),
    ("silicon", "tencent/Hunyuan-MT-7B"): CapabilityProfile(
        provider="silicon",
        model_name="tencent/Hunyuan-MT-7B",
        capability_profile_version="silicon/hunyuan-mt-7b@1",
        window_shape="combined",
        context_window_tokens=32_768,
        max_output_tokens=2_048,
        default_output_reserve_tokens=1_024,
        tokenizer_family="hunyuan",
    ),
    ("silicon", "tencent/Hunyuan-A13B-Instruct"): CapabilityProfile(
        provider="silicon",
        model_name="tencent/Hunyuan-A13B-Instruct",
        capability_profile_version="silicon/hunyuan-a13b-instruct@1",
        window_shape="combined",
        context_window_tokens=131_072,
        max_output_tokens=8_192,
        default_output_reserve_tokens=4_096,
        tokenizer_family="hunyuan",
    ),
}
