#!/usr/bin/env python3
"""Generate idempotent backfill SQL from capability_profiles.CATALOG.

Usage:
    python deploy/sql/migrations/generate_backfill_sql.py > deploy/sql/migrations/v2.2.x_MMDD_backfill_from_catalog.sql

Run whenever capability_profiles.py changes, then commit the generated SQL.
"""
import sys
import os
import types
from datetime import date
from collections import namedtuple

_project_root = os.path.join(os.path.dirname(__file__), "..", "..", "..")
sys.path.insert(0, os.path.join(_project_root, "backend"))

# Stub SDK types to avoid pulling in the full nexent SDK dependency chain
_nexent_stub = types.ModuleType("nexent")
_nexent_core = types.ModuleType("nexent.core")
_nexent_models = types.ModuleType("nexent.core.models")
_nexent_resolver = types.ModuleType("nexent.core.models.capacity_resolver")

ProfileKey = tuple

class CapabilityProfile:
    """Minimal stub that accepts any keyword arguments."""
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

_nexent_resolver.ProfileKey = ProfileKey
_nexent_resolver.CapabilityProfile = CapabilityProfile
sys.modules["nexent"] = _nexent_stub
sys.modules["nexent.core"] = _nexent_core
sys.modules["nexent.core.models"] = _nexent_models
sys.modules["nexent.core.models.capacity_resolver"] = _nexent_resolver

from consts.capability_profiles import CATALOG, CATALOG_REVISION

DEFAULT_CONTEXT_WINDOW = 32_768
DEFAULT_MAX_OUTPUT = 4_096
DEFAULT_RESERVE = 4_096


def _sql_int(value: int) -> str:
    return str(value)


def _sql_str(value: str) -> str:
    return value.replace("'", "''")


def _split_repo_name(full_id: str) -> tuple[str, str]:
    """Split a catalog's full model identifier into (model_repo, model_name).

    Must match backend/utils/model_name_utils.split_repo_name which splits
    on the LAST '/' (rsplit). For 'Pro/deepseek-ai/DeepSeek-V3.2' this
    yields repo='Pro/deepseek-ai', name='DeepSeek-V3.2'.
    """
    if "/" in full_id:
        repo, name = full_id.rsplit("/", 1)
        return repo, name
    return "", full_id


def _sql_repo_match(repo: str) -> str:
    """Build the WHERE fragment that matches the table's model_repo column.

    Bare-name catalog entries (no '/') can land in the table as either
    model_repo='' or model_repo IS NULL depending on the create path, so
    accept both. Namespaced entries match the exact string.
    """
    if repo == "":
        return "(model_repo IS NULL OR model_repo = '')"
    return f"model_repo = '{_sql_str(repo)}'"


def main() -> None:
    today = date.today().strftime("%Y-%m-%d")
    lines: list[str] = []

    lines.append(f"-- Generated by deploy/sql/migrations/generate_backfill_sql.py on {today}")
    lines.append(f"-- Catalog revision: {CATALOG_REVISION}")
    lines.append(f"-- Catalog entries: {len(CATALOG)}")
    lines.append("--")
    lines.append("-- Migration kind: RECOMMENDED_DATA_FIX")
    lines.append("-- Idempotent: COALESCE + IS NULL guards protect existing values.")
    lines.append("-- Safe: enforces max_output < context_window via GREATEST/LEAST.")
    lines.append("--")
    lines.append("-- Phases:")
    lines.append("--   1a  Bare LLM/VLM rows that match a catalog entry by")
    lines.append("--       (model_factory, model_repo, model_name) -> fill capacity")
    lines.append("--       fields + tag capacity_source='profile' + profile_version.")
    lines.append("--   1b  Already-filled rows that match a catalog entry AND whose")
    lines.append("--       context_window_tokens and max_output_tokens exactly equal")
    lines.append("--       the catalog values -> tag profile_version only. capacity_")
    lines.append("--       source stays whatever it was (typically 'operator'); we")
    lines.append("--       don't rewrite provenance, we just add the dispatch tag so")
    lines.append("--       dispatch_profile_hit_total can fire.")
    lines.append("--    2  Remaining bare LLM/VLM rows -> safe defaults.")
    lines.append("--    3  Clamp default_output_reserve_tokens to <= max_output_tokens.")
    lines.append("--")
    lines.append("-- Pre-run self-check (rows whose capability_profile_version is NULL):")
    lines.append("--")
    lines.append("--   SELECT model_id, model_repo, model_name, model_factory,")
    lines.append("--          context_window_tokens, max_output_tokens, capability_profile_version")
    lines.append("--     FROM nexent.model_record_t")
    lines.append("--    WHERE delete_flag = 'N'")
    lines.append("--      AND COALESCE(model_type, 'llm') IN ('llm', 'vlm')")
    lines.append("--      AND capability_profile_version IS NULL;")
    lines.append("")

    # Group catalog by provider so the generated SQL has tidy section headers
    from collections import defaultdict
    by_provider: dict[str, list] = defaultdict(list)
    for (provider, full_id), profile in CATALOG.items():
        by_provider[provider].append((full_id, profile))

    # --------------------------------------------------------------
    # Phase 1a: catalog match + bare -> fill capacity + tag
    # --------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- Phase 1a: Backfill bare rows that match approved catalog entries")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("    v_total   INTEGER := 0;")
    lines.append("    c_active_flag     CONSTANT TEXT := 'N';")
    lines.append("    c_source_profile  CONSTANT TEXT := 'profile';")
    lines.append("BEGIN")

    for provider in sorted(by_provider.keys()):
        entries = by_provider[provider]
        lines.append(f"    -- {provider} ({len(entries)} entries)")
        for full_id, profile in entries:
            ctx = profile.context_window_tokens
            mout = profile.max_output_tokens
            reserve = profile.default_output_reserve_tokens
            version = _sql_str(profile.capability_profile_version)
            repo, name = _split_repo_name(full_id)
            repo_match = _sql_repo_match(repo)
            escaped_name = _sql_str(name)

            lines.append(f"    UPDATE nexent.model_record_t")
            lines.append(f"       SET context_window_tokens = COALESCE(context_window_tokens,")
            lines.append(f"           GREATEST({_sql_int(ctx)}, COALESCE(max_output_tokens, 0) + 1)),")
            lines.append(f"           max_output_tokens = COALESCE(max_output_tokens,")
            lines.append(f"           LEAST({_sql_int(mout)}, COALESCE(context_window_tokens, {_sql_int(ctx)}) - 1)),")
            lines.append(f"           default_output_reserve_tokens = COALESCE(default_output_reserve_tokens,")
            lines.append(f"           LEAST({_sql_int(reserve)}, COALESCE(max_output_tokens, {_sql_int(mout)}))),")
            lines.append(f"           capacity_source = COALESCE(capacity_source, c_source_profile),")
            lines.append(f"           capability_profile_version = COALESCE(capability_profile_version, '{version}')")
            lines.append(f"     WHERE LOWER(model_factory) = '{_sql_str(provider.lower())}'")
            lines.append(f"       AND {repo_match}")
            lines.append(f"       AND model_name = '{escaped_name}'")
            lines.append(f"       AND delete_flag = c_active_flag")
            lines.append(f"       AND (context_window_tokens IS NULL OR max_output_tokens IS NULL);")
            lines.append(f"    GET DIAGNOSTICS v_updated = ROW_COUNT;")
            lines.append(f"    v_total := v_total + v_updated;")
            lines.append("")

    lines.append("    RAISE NOTICE 'Phase 1a catalog backfill (bare): % row(s) updated', v_total;")
    lines.append("END $$;")
    lines.append("")

    # --------------------------------------------------------------
    # Phase 1b: catalog match + already-filled values match catalog
    #           -> tag profile_version + upgrade capacity_source from 'default' to 'profile'
    # --------------------------------------------------------------
    lines.append("-- ============================================================")
    lines.append("-- Phase 1b: Tag already-filled rows whose ctx/max_out exactly match")
    lines.append("--           the catalog with capability_profile_version. Upgrades")
    lines.append("--           capacity_source from 'default' to 'profile' (values now")
    lines.append("--           come from catalog, not system defaults). Preserves")
    lines.append("--           'operator' and other explicit sources.")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("    v_total   INTEGER := 0;")
    lines.append("    c_active_flag     CONSTANT TEXT := 'N';")
    lines.append("    c_source_default  CONSTANT TEXT := 'default';")
    lines.append("    c_source_profile  CONSTANT TEXT := 'profile';")
    lines.append("BEGIN")

    for provider in sorted(by_provider.keys()):
        entries = by_provider[provider]
        lines.append(f"    -- {provider} ({len(entries)} entries)")
        for full_id, profile in entries:
            ctx = profile.context_window_tokens
            mout = profile.max_output_tokens
            version = _sql_str(profile.capability_profile_version)
            repo, name = _split_repo_name(full_id)
            repo_match = _sql_repo_match(repo)
            escaped_name = _sql_str(name)

            lines.append(f"    UPDATE nexent.model_record_t")
            lines.append(f"       SET capability_profile_version = '{version}',")
            lines.append(f"           capacity_source = CASE WHEN capacity_source = c_source_default THEN c_source_profile ELSE capacity_source END")
            lines.append(f"     WHERE LOWER(model_factory) = '{_sql_str(provider.lower())}'")
            lines.append(f"       AND {repo_match}")
            lines.append(f"       AND model_name = '{escaped_name}'")
            lines.append(f"       AND delete_flag = c_active_flag")
            lines.append(f"       AND context_window_tokens = {_sql_int(ctx)}")
            lines.append(f"       AND max_output_tokens = {_sql_int(mout)}")
            lines.append(f"       AND (capability_profile_version IS NULL OR (capability_profile_version = '{version}' AND capacity_source = c_source_default));")
            lines.append(f"    GET DIAGNOSTICS v_updated = ROW_COUNT;")
            lines.append(f"    v_total := v_total + v_updated;")
            lines.append("")

    lines.append("    RAISE NOTICE 'Phase 1b catalog tag (matching filled): % row(s) updated', v_total;")
    lines.append("END $$;")
    lines.append("")

    # Phase 2: safe defaults for remaining bare rows
    lines.append("-- ============================================================")
    lines.append("-- Phase 2: Safe defaults for remaining bare LLM/VLM rows")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("    c_active_flag     CONSTANT TEXT := 'N';")
    lines.append("    c_source_default  CONSTANT TEXT := 'default';")
    lines.append("BEGIN")
    lines.append("    UPDATE nexent.model_record_t")
    lines.append(f"       SET context_window_tokens = COALESCE(context_window_tokens,")
    lines.append(f"           GREATEST({_sql_int(DEFAULT_CONTEXT_WINDOW)}, COALESCE(max_output_tokens, 0) + 1)),")
    lines.append(f"           max_output_tokens = COALESCE(max_output_tokens,")
    lines.append(f"           LEAST({_sql_int(DEFAULT_MAX_OUTPUT)}, COALESCE(context_window_tokens, {_sql_int(DEFAULT_CONTEXT_WINDOW)}) - 1)),")
    lines.append(f"           default_output_reserve_tokens = COALESCE(default_output_reserve_tokens,")
    lines.append(f"           LEAST({_sql_int(DEFAULT_RESERVE)}, COALESCE(max_output_tokens, {_sql_int(DEFAULT_MAX_OUTPUT)}))),")
    lines.append(f"           capacity_source = COALESCE(capacity_source, c_source_default)")
    lines.append("     WHERE delete_flag = c_active_flag")
    lines.append("       AND COALESCE(model_type, 'llm') IN ('llm', 'vlm')")
    lines.append("       AND (context_window_tokens IS NULL OR max_output_tokens IS NULL);")
    lines.append("")
    lines.append("    GET DIAGNOSTICS v_updated = ROW_COUNT;")
    lines.append("    RAISE NOTICE 'Safe defaults: % LLM/VLM row(s) backfilled', v_updated;")
    lines.append("END $$;")
    lines.append("")

    # Phase 3: clamp reserve to max_output
    lines.append("-- ============================================================")
    lines.append("-- Phase 3: Clamp default_output_reserve_tokens to max_output_tokens")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("    c_active_flag     CONSTANT TEXT := 'N';")
    lines.append("BEGIN")
    lines.append("    UPDATE nexent.model_record_t")
    lines.append("       SET default_output_reserve_tokens = max_output_tokens")
    lines.append("     WHERE delete_flag = c_active_flag")
    lines.append("       AND default_output_reserve_tokens IS NOT NULL")
    lines.append("       AND max_output_tokens IS NOT NULL")
    lines.append("       AND default_output_reserve_tokens > max_output_tokens;")
    lines.append("")
    lines.append("    GET DIAGNOSTICS v_updated = ROW_COUNT;")
    lines.append("    RAISE NOTICE 'reserve clamp: % row(s) updated', v_updated;")
    lines.append("END $$;")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
