apiVersion: v2
name: nexent-supabase-db
description: Nexent Supabase DB - Supabase PostgreSQL database
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - nexent
  - supabase
  - postgresql
  - database
maintainers:
  - name: Nexent Team
dependencies:
  - name: nexent-common
    version: 0.1.0
    repository: "file://../nexent-common"
