replicaCount: 1

image:
  repository: supabase/postgres
  tag: 15.8.1.060
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 256Mi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1

storage:
  size: 10Gi
  hostPath: "/var/lib/nexent-data/nexent-supabase-db"

config:
  postgresDb: "supabase"
  postgresPort: "5436"
  jwtExpiry: "3600"
