{{- if or (eq .Values.global.deploymentVersion "full") (index .Values.global.deploymentComponents "supabase") }}
---
apiVersion: v1
kind: Service
metadata:
  name: nexent-supabase-db
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: {{ .Values.config.postgresPort | int }}
      targetPort: {{ .Values.config.postgresPort | int }}
      name: postgres
      {{- if and (eq (default "ClusterIP" .Values.service.type) "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: nexent-supabase-db
{{- end }}
