apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexent-redis-pv
  labels:
    type: local
    app: nexent-redis
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: hostpath
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexent-redis
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  volumeName: nexent-redis-pv
  storageClassName: hostpath
