{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexent-openssh-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nexent-openssh-server
  annotations:
    "helm.sh/hook-weight": "25"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nexent-openssh-server
  template:
    metadata:
      labels:
        app: nexent-openssh-server
    spec:
      containers:
        - name: openssh-server
          image: {{ .Values.images.openssh.repository }}:{{ .Values.images.openssh.tag }}
          imagePullPolicy: {{ .Values.images.openssh.pullPolicy }}
          ports:
            - containerPort: 22
              name: ssh
          env:
            - name: DEV_USER
              valueFrom:
                secretKeyRef:
                  name: nexent-secrets
                  key: SSH_USERNAME
            - name: DEV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexent-secrets
                  key: SSH_PASSWORD
          resources:
            requests:
              memory: {{ .Values.resources.openssh.requests.memory }}
              cpu: {{ .Values.resources.openssh.requests.cpu }}
            limits:
              memory: {{ .Values.resources.openssh.limits.memory }}
              cpu: {{ .Values.resources.openssh.limits.cpu }}
{{- end }}
