apiVersion: v1
kind: Service
metadata:
  name: nexent-elasticsearch
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nexent-elasticsearch
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
    - port: 9200
      targetPort: 9200
      name: http
      {{- if and (eq (default "ClusterIP" .Values.service.type) "NodePort") .Values.service.nodePorts.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    - port: 9300
      targetPort: 9300
      name: transport
      {{- if and (eq (default "ClusterIP" .Values.service.type) "NodePort") .Values.service.nodePorts.transport }}
      nodePort: {{ .Values.service.nodePorts.transport }}
      {{- end }}
  selector:
    app: nexent-elasticsearch
